Return-Path: <gwml-bounces@gnuweeb.org>
Delivered-To: sprite@gnuweeb.org
Received: from gnuweeb.org
	by gnuweeb with LMTP
	id neqbGyGI52GtHAYAav/0+A
	(envelope-from <gwml-bounces@gnuweeb.org>)
	for <sprite@gnuweeb.org>; Wed, 19 Jan 2022 03:40:17 +0000
Received: from [127.0.0.1] (localhost [127.0.0.1])
	by gnuweeb.org (Postfix) with ESMTP id 5C492C1660;
	Wed, 19 Jan 2022 03:40:15 +0000 (UTC)
Authentication-Results: gnuweeb.org;
	dkim=fail reason="signature verification failed" (2048-bit key; unprotected) header.d=intel.com header.i=@intel.com header.a=rsa-sha256 header.s=Intel header.b=E4NxDxqV;
	dkim-atps=neutral
X-Original-To: gwml@gnuweeb.org
Delivered-To: gwml@gnuweeb.org
Received: from mga17.intel.com (mga17.intel.com [192.55.52.151])
 by gnuweeb.org (Postfix) with ESMTPS id A306FC0087
 for <gwml@gnuweeb.org>; Wed, 19 Jan 2022 03:40:08 +0000 (UTC)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple;
 d=intel.com; i=@intel.com; q=dns/txt; s=Intel;
 t=1642563609; x=1674099609;
 h=date:from:to:cc:subject:message-id:references:
 mime-version:in-reply-to;
 bh=qAUdyOMpjLXgFKoF0QifDorI3aMIdOzmR0SvIvEQHwA=;
 b=E4NxDxqV00uAG05flt6C3UY+d+nJyZgBCX2VaDRoBBycQyXndN9BC3XE
 puHZCaHNCYlqwp4v0bLpE8Q5U8myPkrYbXWYsniqaMDL3qteeuuZC/3fC
 brAYzzPPAbfLhbJJnDw/qIk04QWidcxiWaStaUZjY87wD7fMManhbA+mM
 4xzhOlfiuN32SDs5Zp9BKRPcFuVpe2IjvuzX8CEdw0HkOWN9wfFoF4yVK
 Fd2tHNuSW/GgI53FRM4SJmIofbGszSqPFUb5238SG39RUkJoDceJivv2B
 zzAkEeJBR6meXsmYSXvWd1MFBWRbD55DLjJdTPuft99m7HEooeV21Z8YX g==;
X-IronPort-AV: E=McAfee;i="6200,9189,10231"; a="225647438"
X-IronPort-AV: E=Sophos;i="5.88,298,1635231600"; d="scan'208";a="225647438"
Received: from orsmga004.jf.intel.com ([10.7.209.38])
 by fmsmga107.fm.intel.com with ESMTP/TLS/ECDHE-RSA-AES256-GCM-SHA384;
 18 Jan 2022 19:39:17 -0800
X-ExtLoop1: 1
X-IronPort-AV: E=Sophos;i="5.88,298,1635231600"; d="scan'208";a="625735673"
Received: from lkp-server01.sh.intel.com (HELO 276f1b88eecb) ([10.239.97.150])
 by orsmga004.jf.intel.com with ESMTP; 18 Jan 2022 19:39:15 -0800
Received: from kbuild by 276f1b88eecb with local (Exim 4.92)
 (envelope-from <lkp@intel.com>)
 id 1nA1oZ-000DDD-4k; Wed, 19 Jan 2022 03:39:15 +0000
Date: Wed, 19 Jan 2022 11:38:36 +0800
From: kernel test robot <lkp@intel.com>
To: Alexandre Ghiti <alexandre.ghiti@canonical.com>
Subject: [PATCH] riscv: fix boolconv.cocci warnings
Message-ID: <20220119033836.GA4900@68f8e94b87ce>
References: <202201191124.6Gmmz1ir-lkp@intel.com>
MIME-Version: 1.0
Content-Disposition: inline
In-Reply-To: <202201191124.6Gmmz1ir-lkp@intel.com>
User-Agent: Mutt/1.10.1 (2018-07-13)
X-BeenThere: gwml@gnuweeb.org
X-Mailman-Version: 2.1.29
Precedence: list
List-Id: GNU/Weeb Mailing List <gwml.gnuweeb.org>
List-Unsubscribe: <https://gwml.gnuweeb.org/options/gwml>,
 <mailto:gwml-request@gnuweeb.org?subject=unsubscribe>
List-Archive: <http://gwml.gnuweeb.org/pipermail/gwml/>
List-Post: <mailto:gwml@gnuweeb.org>
List-Help: <mailto:gwml-request@gnuweeb.org?subject=help>
List-Subscribe: <https://gwml.gnuweeb.org/listinfo/gwml>,
 <mailto:gwml-request@gnuweeb.org?subject=subscribe>
Reply-To: GNU/Weeb Mailing List <gwml@gnuweeb.org>
Cc: GNU/Weeb Mailing List <gwml@gnuweeb.org>, kbuild-all@lists.01.org,
 linux-kernel@vger.kernel.org, Palmer Dabbelt <palmer@rivosinc.com>
Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: 7bit
Errors-To: gwml-bounces@gnuweeb.org
Sender: "GWML" <gwml-bounces@gnuweeb.org>

From: kernel test robot <lkp@intel.com>

arch/riscv/mm/init.c:48:11-16: WARNING: conversion to bool not needed here

 Remove unneeded conversion to bool

Semantic patch information:
 Relational and logical operators evaluate to bool,
 explicit conversion is overly verbose and unneeded.

Generated by: scripts/coccinelle/misc/boolconv.cocci

CC: Alexandre Ghiti <alexandre.ghiti@canonical.com>
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: kernel test robot <lkp@intel.com>
---

tree:   https://github.com/ammarfaizi2/linux-block palmer/linux/riscv-sv48
head:   d87f3297c62644624bcb8efcb519a2e28d684b45
commit: dee563c628683ce1fab7d0267ad96fc7d8503965 [7/9] riscv: Implement sv48 support
:::::: branch date: 8 hours ago
:::::: commit date: 8 hours ago

 init.c |    3 +--
 1 file changed, 1 insertion(+), 2 deletions(-)

--- a/arch/riscv/mm/init.c
+++ b/arch/riscv/mm/init.c
@@ -44,8 +44,7 @@ u64 satp_mode = SATP_MODE_32;
 #endif
 EXPORT_SYMBOL(satp_mode);
 
-bool pgtable_l4_enabled = IS_ENABLED(CONFIG_64BIT) && !IS_ENABLED(CONFIG_XIP_KERNEL) ?
-				true : false;
+bool pgtable_l4_enabled = IS_ENABLED(CONFIG_64BIT) && !IS_ENABLED(CONFIG_XIP_KERNEL);
 EXPORT_SYMBOL(pgtable_l4_enabled);
 
 phys_addr_t phys_ram_base __ro_after_init;
-- 
GWML mailing list
GWML@gnuweeb.org
https://gwml.gnuweeb.org/listinfo/gwml
