Return-Path: <gwml-bounces@gnuweeb.org>
Delivered-To: sprite@gnuweeb.org
Received: from gnuweeb.org
	by gnuweeb with LMTP
	id oLDoAhPRtmAvSgUAav/0+A
	(envelope-from <gwml-bounces@gnuweeb.org>)
	for <sprite@gnuweeb.org>; Wed, 02 Jun 2021 00:30:11 +0000
Received: from [127.0.0.1] (localhost [127.0.0.1])
	by gnuweeb.org (Postfix) with ESMTP id 99DA5C2B3D;
	Wed,  2 Jun 2021 00:30:10 +0000 (UTC)
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=gnuweeb.org;
	s=default; t=1622593810;
	bh=Fo32c2o/dQfVdDm4oNIx7XUpXTZFCA+AHN9eajesu14=;
	h=Subject:From:To:References:Date:In-Reply-To:List-Id:
	 List-Unsubscribe:List-Archive:List-Post:List-Help:List-Subscribe:
	 Reply-To:From;
	b=IHe3QOmIWgMgg6vwDTriViwdVLbM+EI9osk/gQmmbpziLnKryuMW8GR/fMxNFGvIK
	 746TVejQ5rRYDEGea+hQy8rA0GHuVcn61UNaTjWZEItckmgR8JW7y3UD4a4IoITG6v
	 Rtv4pVs5uRszfFSVv+UdBFaYXFC7dLk2IYOaJ+Uw7uh5TUj3/oAIRAQQMLVfjNR/T1
	 0dSl8wBLfVUchLe2cqVcm9wY7hv/K0WGFR4BQgz36zVaj/7GnWcFXnq2IlYYDxURY6
	 u+DaNHiNNMvp84gQEpqI+qj/JBb2r10hUY3kF0G7JbKqZuiJZOa0B+VeCycg0v9Mw0
	 wYQcwLT++XpsA==
X-Original-To: gwml@gnuweeb.org
Delivered-To: gwml@gnuweeb.org
Received: from [10.7.7.2] (unknown [68.183.184.174])
 by gnuweeb.org (Postfix) with ESMTPSA id 513D5C159A
 for <gwml@gnuweeb.org>; Wed,  2 Jun 2021 00:30:08 +0000 (UTC)
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=gnuweeb.org;
 s=default; t=1622593808;
 bh=w1Uen7Crp/8EMf/6J7ioYtfg2l35aOQJbc4u2E6hN2Q=;
 h=Subject:From:To:References:Date:In-Reply-To:From;
 b=awQQKfWndoAqoIS8x8xKNCt8Ky5MWO8T82p89dCGlfKmTAYF14faNagm4yQZj1FYY
 Hk2EGd5ElBI2ARLPk40JG8va+6ulBXUyRj6r4a5uLv/lZ73p/ELvzPzdZBvXgl5hfb
 6PqDvZcFgHeL7UGukfq7axTsagHSul2+5+xA8iuiULhuL2l6F/1hc+xHhBzTR/jMVx
 y/Pw3SJak/bRSx0vScfiw/u75RLP5v3p9u7jJ94IpueWpM/1JreApzYBYnDuopxII0
 zDT2TqDKHoOW40ixJrnjPxIMQbDguD2Tx57dXSKnp+aKi8fvUS8tAJAZkm5Y+xo+Lt
 wZWdIYosWETGA==
Subject: Re: [Quiz] Exploit Buffer Overflow Vulnerability
From: Ammar Faizi <ammarfaizi2@gnuweeb.org>
To: gwml@gnuweeb.org
References: <50e30bfc-8410-de1c-d720-964f5c7a4a20@gnuweeb.org>
Message-ID: <ed65a2ef-c397-7684-a96c-27e13369dc6f@gnuweeb.org>
Date: Wed, 2 Jun 2021 07:30:06 +0700
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101
 Thunderbird/78.8.1
MIME-Version: 1.0
In-Reply-To: <50e30bfc-8410-de1c-d720-964f5c7a4a20@gnuweeb.org>
Content-Language: en-US
X-BeenThere: gwml@gnuweeb.org
X-Mailman-Version: 2.1.29
Precedence: list
List-Id: GNU/Weeb Mailing List <gwml.gnuweeb.org>
List-Unsubscribe: <https://gwml.gnuweeb.org/options/gwml>,
 <mailto:gwml-request@gnuweeb.org?subject=unsubscribe>
List-Archive: <http://gwml.gnuweeb.org/pipermail/gwml/>
List-Post: <mailto:gwml@gnuweeb.org>
List-Help: <mailto:gwml-request@gnuweeb.org?subject=help>
List-Subscribe: <https://gwml.gnuweeb.org/listinfo/gwml>,
 <mailto:gwml-request@gnuweeb.org?subject=subscribe>
Reply-To: GNU/Weeb Mailing List <gwml@gnuweeb.org>
Content-Transfer-Encoding: base64
Content-Type: text/plain; charset="utf-8"; Format="flowed"
Errors-To: gwml-bounces@gnuweeb.org
Sender: "GWML" <gwml-bounces@gnuweeb.org>

SGkgZXZlcnlvbmUsCgpCZWxvdyBpcyB0aGUgd3JpdGUgdXAgb2YgdGhlIGxhdGVzdCBxdWl6LgoK
SXQgaXMga25vd24gdGhhdCB0aGUgdnVsbmVyYWJpbGl0eSBpcyBsb2NhdGVkIG9uIGBnZXRfaW5w
dXRgIGZ1bmN0aW9uLgoKIMKgIDAwMDAwMDAwMDA0MDEwNzQgPGdldF9pbnB1dD46CiDCoMKgwqAg
NDAxMDc0OsKgwqDCoMKgwqDCoCBwdXNowqDCoCAlcmJwCiDCoMKgwqAgNDAxMDc1OsKgwqDCoMKg
wqDCoCBtb3bCoMKgwqAgJXJzcCwlcmJwCiDCoMKgwqAgNDAxMDc4OsKgwqDCoMKgwqDCoCBzdWLC
oMKgwqAgJDB4MWY4LCVyc3AKIMKgwqDCoCA0MDEwN2Y6wqDCoMKgwqDCoMKgIGxlYcKgwqDCoCAw
eGZlYiglcmlwKSwlcnNpwqDCoMKgwqDCoMKgwqAgIyA0MDIwNzEgPHN0cjQ+CiDCoMKgwqAgNDAx
MDg2OsKgwqDCoMKgwqDCoCBtb3bCoMKgwqAgJDB4MSwlZWF4CiDCoMKgwqAgNDAxMDhiOsKgwqDC
oMKgwqDCoCBtb3bCoMKgwqAgJDB4MSwlZWRpCiDCoMKgwqAgNDAxMDkwOsKgwqDCoMKgwqDCoCBt
b3bCoMKgwqAgJDB4MTMsJWVkeAogwqDCoMKgIDQwMTA5NTrCoMKgwqDCoMKgwqAgc3lzY2FsbAog
wqDCoMKgIDQwMTA5NzrCoMKgwqDCoMKgwqAgbGVhwqDCoMKgIC0weDFmOCglcmJwKSwlcnNpCiDC
oMKgwqAgNDAxMDllOsKgwqDCoMKgwqDCoCB4b3LCoMKgwqAgJWVheCwlZWF4CiDCoMKgwqAgNDAx
MGEwOsKgwqDCoMKgwqDCoCB4b3LCoMKgwqAgJWVkaSwlZWRpCiDCoMKgwqAgNDAxMGEyOsKgwqDC
oMKgwqDCoCBtb3bCoMKgwqAgJDB4MTAwMCwlZWR4wqAgIyBUaGUgaG9sZSBpcyBoZXJlLi4uCiDC
oMKgwqAgNDAxMGE3OsKgwqDCoMKgwqDCoCBzeXNjYWxsCiDCoMKgwqAgNDAxMGE5OsKgwqDCoMKg
wqDCoCBtb3bCoMKgwqAgJXJicCwlcnNwCiDCoMKgwqAgNDAxMGFjOsKgwqDCoMKgwqDCoCBwb3DC
oMKgwqAgJXJicAogwqDCoMKgIDQwMTBhZDrCoMKgwqDCoMKgwqAgbW92wqDCoMKgICglcnNwKSwl
cmRpCiDCoMKgwqAgNDAxMGIxOsKgwqDCoMKgwqDCoCBtb3bCoMKgwqAgJXJkaSwweDFmY2MoJXJp
cCnCoMKgwqDCoMKgwqDCoCAjIDQwMzA4NCA8cmV0X2FkZHI+CiDCoMKgwqAgNDAxMGI4OsKgwqDC
oMKgwqDCoCByZXQKCkluIHRoaXMgY2FzZSwgdGhlIGJ1ZmZlciBpcyBvbmx5IDB4MWY4IGJ5dGVz
LCBidXQgdGhlIHN5c2NhbGwgcmVhZCgpCm1heSB3cml0ZSAweDEwMDAgYnl0ZXMgdG8gdGhhdCBt
ZW1vcnkuCgpDb25zaWRlciB0aGUgZm9sbG93aW5nIHN0YWNrIGxheW91dDoKCiDCoMKgwqDCoMKg
ICVyc3AgLS0tLT7CoCB8wqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgIHwKIMKg
wqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqAgfMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDC
oMKgwqDCoMKgwqDCoCB8CiDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgIHzCoMKg
wqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqAgfAogwqDCoMKgwqDCoMKgwqDCoMKgwqDC
oMKgwqDCoMKgwqDCoCB8wqAgNTA0IGJ5dGVzIGJ1ZmZlciB8CiDCoMKgwqDCoMKgwqDCoMKgwqDC
oMKgwqDCoMKgwqDCoMKgIHzCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqAgfAog
wqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoCB8wqDCoMKgwqDCoMKgwqDCoMKgwqDC
oMKgwqDCoMKgwqDCoMKgIHwKIMKgNTA0ICsgJXJzcCAtLS0tPiB8LS0tLS0tLS0tLS0tLS0tLS0t
LXwgPC0tLS0gJXJicAogwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoCB8wqDCoMKg
wqDCoCBPbGQgJXJicMKgwqDCoMKgIHwKIMKgNTEyICsgJXJzcCAtLS0tPiB8LS0tLS0tLS0tLS0t
LS0tLS0tLXwKIMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqAgfMKgwqAgUmV0dXJu
IEFkZHJlc3PCoCB8CiDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgwqDCoMKgIHwtLS0tLS0t
LS0tLS0tLS0tLS0tfAoKCk5vdywgd2hhdCB3ZSBuZWVkIHRvIGRvIGlzIG92ZXJ3cml0ZSB0aGUg
cmV0dXJuIGFkZHJlc3MsIHNvIHRoYXQgd2hlbgp0aGUgYGdldF9pbnB1dGAgZnVuY3Rpb24gcmV0
dXJucywgd2UgY2FuIG92ZXJyaWRlICVyaXAgYW5kIHJlYWNoIHRoZQpzZWNyZXRfZnVuYy4gRXhh
bWluZSB0aGUgZm9sbG93aW5nIG9iamR1bXAgcmVzdWx0OgoKIMKgIDAwMDAwMDAwMDA0MDEwYjkg
PHNlY3JldF9mdW5jPjoKIMKgwqDCoCA0MDEwYjk6IHB1c2jCoMKgICVyYnAKIMKgwqDCoCA0MDEw
YmE6IG1vdsKgwqDCoCAlcnNwLCVyYnAKIMKgwqDCoCA0MDEwYmQ6IG1vdsKgwqDCoCAweDFmYzAo
JXJpcCksJXI4wqDCoMKgwqDCoMKgwqAgIyA0MDMwODQgPHJldF9hZGRyPgoKIMKgIDAwMDAwMDAw
MDA0MDEwYzQgPC5fZG9fY2hlY2s+OgogwqDCoMKgIDQwMTBjNDogbGVhwqDCoMKgIC0weDEyKCVy
aXApLCVyYXjCoMKgwqDCoMKgwqDCoCAjIDQwMTBiOSA8c2VjcmV0X2Z1bmM+CiDCoMKgwqAgNDAx
MGNiOiBjbXDCoMKgwqAgJXJheCwlcjgKIMKgwqDCoCA0MDEwY2U6IGpuZcKgwqDCoCA0MDExMmYg
PC5fZW5kX3dyb25nPgogwqDCoMKgIDQwMTBkMDogbW92wqDCoMKgICQweGZmZmZmZmZmZmZmZmZm
ZmYsJXJheAogwqDCoMKgIDQwMTBkNzogY21wwqDCoMKgICVyYXgsMHgwKCVyYnApCiDCoMKgwqAg
NDAxMGRiOiBqbmXCoMKgwqAgNDAxMTJmIDwuX2VuZF93cm9uZz4KCiDCoCAwMDAwMDAwMDAwNDAx
MGRkIDwuX2VuZF9kb19jaGVjaz46CiDCoMKgwqAgNDAxMGRkOiBsZWHCoMKgwqAgMHhmMWMoJXJp
cCksJXJzacKgwqDCoMKgwqDCoMKgICMgNDAyMDAwIDxzdHIxPgogwqDCoMKgIDQwMTBlNDogbW92
wqDCoMKgICQweDEsJWVkaQogwqDCoMKgIDQwMTBlOTogbW92wqDCoMKgICQweDJiLCVlZHgKIMKg
wqDCoCA0MDEwZWU6IG1vdsKgwqDCoCAweDAoJXJicCksJXJjeAogwqDCoMKgIDQwMTBmMjogYW5k
wqDCoMKgICVyYXgsJXJjeAogwqDCoMKgIDQwMTBmNTogbW92wqDCoMKgICVyY3gsJXJheAogwqDC
oMKgIDQwMTBmODogbW92wqDCoMKgICVyY3gsJXJkaQogwqDCoMKgIDQwMTBmYjogbmVnwqDCoMKg
ICVyYXgKIMKgwqDCoCA0MDEwZmU6IG5lZ8KgwqDCoCAlcmRpCiDCoMKgwqAgNDAxMTAxOiBhbmTC
oMKgwqAgJXJjeCwlcnNpCiDCoMKgwqAgNDAxMTA0OiBhbmTCoMKgwqAgJXJjeCwlcmR4CiDCoMKg
wqAgNDAxMTA3OiBhbmTCoMKgwqAgJXJjeCwlcnNwCiDCoMKgwqAgNDAxMTBhOiBsZWHCoMKgwqAg
LTB4NTgoJXJpcCksJXJjeMKgwqDCoMKgwqDCoMKgICMgNDAxMGI5IDxzZWNyZXRfZnVuYz4KIMKg
wqDCoCA0MDExMTE6IHhvcsKgwqDCoCAlcjgsJXJjeAogwqDCoMKgIDQwMTExNDogb3LCoMKgwqDC
oCAlcmN4LCVyYXgKIMKgwqDCoCA0MDExMTc6IG9ywqDCoMKgwqAgJXJjeCwlcmRpCiDCoMKgwqAg
NDAxMTFhOiBvcsKgwqDCoMKgICVyY3gsJXJzaQogwqDCoMKgIDQwMTExZDogb3LCoMKgwqDCoCAl
cmN4LCVyZHgKIMKgwqDCoCA0MDExMjA6IG9ywqDCoMKgwqAgJXJjeCwlcnNwCiDCoMKgwqAgNDAx
MTIzOiBjbXDCoMKgwqAgJDB4MSwlcmF4CiDCoMKgwqAgNDAxMTI3OiBqbmXCoMKgwqAgNDAxMTJm
IDwuX2VuZF93cm9uZz4KIMKgwqDCoCA0MDExMjk6IHN5c2NhbGwKIMKgwqDCoCA0MDExMmI6IHhv
csKgwqDCoCAlZWF4LCVlYXgKIMKgwqDCoCA0MDExMmQ6IGptcMKgwqDCoCA0MDExNGMgPC5yZXRf
c2VjPgoKIMKgIDAwMDAwMDAwMDA0MDExMmYgPC5fZW5kX3dyb25nPjoKIMKgwqDCoCA0MDExMmY6
IGxlYcKgwqDCoCAweGYzYiglcmlwKSwlcnNpwqDCoMKgwqDCoMKgwqAgIyA0MDIwNzEgPHN0cjQ+
CiDCoMKgwqAgNDAxMTM2OiBtb3bCoMKgwqAgJDB4MTMsJWVkeAogwqDCoMKgIDQwMTEzYjogbW92
wqDCoMKgICQweDEsJWVheAogwqDCoMKgIDQwMTE0MDogbW92wqDCoMKgICQweDEsJWVkaQogwqDC
oMKgIDQwMTE0NTogc3lzY2FsbAogwqDCoMKgIDQwMTE0NzogbW92wqDCoMKgICQweDEsJWVheAoK
IMKgIDAwMDAwMDAwMDA0MDExNGMgPC5yZXRfc2VjPjoKIMKgwqDCoCA0MDExNGM6IG1vdsKgwqDC
oCAlcmJwLCVyc3AKIMKgwqDCoCA0MDExNGY6IHBvcMKgwqDCoCAlcmJwCiDCoMKgwqAgNDAxMTUw
OiBsZWHCoMKgwqAgLTB4MTJiKCVyaXApLCVyZGnCoMKgwqDCoMKgwqDCoCAjIDQwMTAyYyA8X2Rv
X2V4aXQ+CiDCoMKgwqAgNDAxMTU3OiBtb3bCoMKgwqAgJXJkaSwoJXJzcCkKIMKgwqDCoCA0MDEx
NWI6IHJldAoKCi0tLS0tLS0tLS0tLS0tLS0tLS0tCkluIHRoaXMgY2FzZSwgd2Ugd2lsbCBqdW1w
IHRvIC5fZW5kX3dyb25nIHdoaWNoIHdpbGwgc2tpcCB0aGUKY29uZ3JhdHVsYXRpb24gbWVzc2Fn
ZSBpZiB3ZSBnbyB0byBpdC4KClRoaXMgY2hlY2sgY29udHJvbHMgdGhlIHBhdGggdG8gYmUgdGFr
ZW46CiDCoMKgwqAgNDAxMGJkOiBtb3bCoMKgwqAgMHgxZmMwKCVyaXApLCVyOMKgwqDCoMKgwqDC
oMKgICMgNDAzMDg0IDxyZXRfYWRkcj4KCiDCoCAwMDAwMDAwMDAwNDAxMGM0IDwuX2RvX2NoZWNr
PjoKIMKgwqDCoCA0MDEwYzQ6IGxlYcKgwqDCoCAtMHgxMiglcmlwKSwlcmF4wqDCoMKgwqDCoMKg
wqAgIyA0MDEwYjkgPHNlY3JldF9mdW5jPgogwqDCoMKgIDQwMTBjYjogY21wwqDCoMKgICVyYXgs
JXI4CiDCoMKgwqAgNDAxMGNlOiBqbmXCoMKgwqAgNDAxMTJmIDwuX2VuZF93cm9uZz4KIMKgwqDC
oCA0MDEwZDA6IG1vdsKgwqDCoCAkMHhmZmZmZmZmZmZmZmZmZmZmLCVyYXgKIMKgwqDCoCA0MDEw
ZDc6IGNtcMKgwqDCoCAlcmF4LDB4MCglcmJwKQogwqDCoMKgIDQwMTBkYjogam5lwqDCoMKgIDQw
MTEyZiA8Ll9lbmRfd3Jvbmc+CgpUaGlzIGV4cGVjdHMgZ2xvYmFsIHZhcmlhYmxlIHJldF9hZGRy
IHRvIGhhdmUgdmFsdWUgdGhlIHNhbWUgd2l0aApzZWNyZXRfZnVuYyBhZGRyZXNzLiBBbmQgYWxz
byBleHBlY3RzIHRoZSBvbGQgJXJicCBiZQoweGZmZmZmZmZmZmZmZmZmZmYgb3IgLTEgKGluIGRl
Y2ltYWwpLgoKU28gd2hhdCB0byBkbz8KIMKgIDEpIEJ5IHVzaW5nIGJ1ZmZlciBvdmVyZmxvdyB2
dWxuZXJhYmlsaXR5LCB3ZSBoYXZlIHRvIHBhdGNoIHRoZQogwqDCoMKgwqAgcmV0dXJuIGFkZHJl
c3Mgc28gdGhhdCBpdCBwb2ludHMgdG8gc2VjcmV0X2Z1bmMuCiDCoCAyKSBQYXRjaCB0aGUgb2xk
ICVyYnAgc28gdGhhdCBpdHMgdmFsdWUgYmUgMHhmZmZmZmZmZmZmZmZmZmZmLgoKQnVpbGRpbmcg
cGF5bG9hZDoKSW4gdGhpcyBjYXNlLCB3ZSBoYXZlIDUwNCB2YWxpZCBidWZmZXIgZm9yIG1lbW9y
eSB3cml0ZS4gU28gd2UgZmlsbAp0aGlzIHZhbGlkIGFyZWEgd2l0aCBhbnl0aGluZy4gSW4gdGhp
cyB3cml0ZSB1cCwgd2UgZmlsbCBpdCB3aXRoICJBIgpjaGFyYWN0ZXIgNTA0IHRpbWVzLgoKQWZ0
ZXIgNTA0IGJ5dGVzIG9mIGJ1ZmZlciwgd2Ugd2lsbCBzdGFydCBwYXRjaGluZyB0aGUgb2xkICVy
YnAgKGlmIHdlCmRvIG1vcmUgOCBieXRlcyB3cml0ZSksIGhlbmNlIHdlIGhhdmUgdG8gZmlsbCBp
dCB3aXRoICJceGZmIiA4IHRpbWVzLgoKQWZ0ZXIgdGhhdCwgd2Ugc3RhcnQgdG91Y2hpbmcgcmV0
dXJuIGFkZHJlc3MuIEFzIHg4Ni02NCBpcyBsaXR0bGUKZW5kaWFuLCB3ZSBoYXZlIHRvIHdyaXRl
IHRoZSBhZGRyZXNzIG9mIHNlY3JldF9mdW5jIGluIHJldmVyc2Ugb3JkZXIKYnJva2VuIGRvd24g
aW50byBjaHVuayBvZiBieXRlcy4KCldpdGggc2ltcGxlIHBlcmwgc2NyaXB0LCB0aGUgcGF5bG9h
ZCB3aWxsIGJlIGxpa2UgdGhpczoKIMKgIHBlcmwgLWUgJ3ByaW50ICJBIng1MDQsIlx4ZmYieDgs
Ilx4YjlceDEwXHg0MCIsIlx4MDAieDUnCgpFeGVjdXRpbmcgZXhwbG9pdDoKIMKgICQgcGVybCAt
ZSAncHJpbnQgIkEieDUwNCwiXHhmZiJ4OCwiXHhiOVx4MTBceDQwIiwiXHgwMCJ4NScgfCAuLzAw
MwogwqAgRW50ZXIgdGhlIGtleXdvcmQ6CiDCoCBDb25ncmF0dWxhdGlvbiwgeW91IGhhdmUgc29s
dmVkIHRoZSBxdWl6IQoKRW5kIG9mIHdyaXRlIHVwLgoKSWYgeW91IGhhdmUgYW55IHF1ZXN0aW9u
IHJlZ2FyZGluZyB0aGUgd3JpdGUgdXAsIGtpbmRseSB0byByZXBseSB0bwp0aGlzIGVtYWlsLCBv
ciBkcm9wIHlvdXIgcXVlc3Rpb24gZGlyZWN0bHkgdG8gVGVsZWdyYW0gZ3JvdXAuCgpIYXBweSBo
YWNraW5nIQoKIMKgIEFtbWFyCgotLSAKR1dNTCBtYWlsaW5nIGxpc3QKR1dNTEBnbnV3ZWViLm9y
ZwpodHRwczovL2d3bWwuZ251d2VlYi5vcmcvbGlzdGluZm8vZ3dtbAo=
